site_name: Rule-ROM Federation ğŸ›ï¸
site_url: https://rulerom.com
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
  custom_dir: ../overrides

extra:
  analytics:
    provider: yandex
    property: 106900883

nav:
  - 'ğŸ›ï¸ Home': index.md
  - 'ğŸ““ Log':
    - 'Overview': log/index.md
    - '2026':
      - '2026 Overview': log/2026/index.md
      - 'January': log/2026/01.md
      - 'February': log/2026/02.md
      - 'March': log/2026/03.md
      - 'April': log/2026/04.md
      - 'May': log/2026/05.md
      - 'June': log/2026/06.md
      - 'July': log/2026/07.md
      - 'August': log/2026/08.md
      - 'September': log/2026/09.md
      - 'October': log/2026/10.md
      - 'November': log/2026/11.md
      - 'December': log/2026/12.md
