site_name: Rule-ROM Federation ğŸ›ï¸
site_url: https://rulerom.com
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
  custom_dir: ../overrides

extra:
  analytics:
    provider: yandex
    property: 106900883

nav:
  - 'ğŸ›ï¸ é¦–é¡µ': index.md
  - 'ğŸ““ æ—¥å¿—':
    - 'æ¦‚è¿°': log/index.md
    - '2026':
      - '2026 æ¦‚è¿°': log/2026/index.md
      - 'ä¸€æœˆ': log/2026/01.md
      - 'äºŒæœˆ': log/2026/02.md
      - 'ä¸‰æœˆ': log/2026/03.md
      - 'å››æœˆ': log/2026/04.md
      - 'äº”æœˆ': log/2026/05.md
      - 'å…­æœˆ': log/2026/06.md
      - 'ä¸ƒæœˆ': log/2026/07.md
      - 'å…«æœˆ': log/2026/08.md
      - 'ä¹æœˆ': log/2026/09.md
      - 'åæœˆ': log/2026/10.md
      - 'åä¸€æœˆ': log/2026/11.md
      - 'åäºŒæœˆ': log/2026/12.md
